sonar.organization=bazilzaidi
sonar.projectKey=BazilZaidi_cohort-9-mern-9273-Bazil
sonar.sources=client/src,server
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.test.js,**/*.test.jsx,**/coverage/**
sonar.sourceEncoding=UTF-8